import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {ThemeProvider} from '@mui/material/styles';
import "../globals.css";
import theme from "@/providers/theme";
import UserProvider from "@/context/authContext";
import Chakra from "@/providers/ChakraProvider";
import DashBoardLayout from "@/components/dashboad/layout/DashBoardLayout";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Suspense>
      <UserProvider>
        <Chakra>
      <ThemeProvider theme={theme}>
        <DashBoardLayout>{children}</DashBoardLayout>
        </ThemeProvider>
        </Chakra>
        </UserProvider>
        </Suspense>
        </body>
    </html>
  );
}